version: '3.0'
services:
  rasa:
    image: pythno/rasa
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run

  app:
  # if pulled from a repo (eg. docker hub) the image name must be username:repo-name
    image: pythno/rasa-actions
    build: Dockerfiles/ActionServer
    expose: ["5055"]